# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jikawa/Downloads/car

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jikawa/Downloads/car

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jikawa/Downloads/car/CMakeFiles /home/jikawa/Downloads/car/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jikawa/Downloads/car/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demo4.x

# Build rule for target.
demo4.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demo4.x
.PHONY : demo4.x

# fast build rule for target.
demo4.x/fast:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/build
.PHONY : demo4.x/fast

building.o: building.cpp.o
.PHONY : building.o

# target to build an object file
building.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/building.cpp.o
.PHONY : building.cpp.o

building.i: building.cpp.i
.PHONY : building.i

# target to preprocess a source file
building.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/building.cpp.i
.PHONY : building.cpp.i

building.s: building.cpp.s
.PHONY : building.s

# target to generate assembly for a file
building.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/building.cpp.s
.PHONY : building.cpp.s

car.o: car.cpp.o
.PHONY : car.o

# target to build an object file
car.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/car.cpp.o
.PHONY : car.cpp.o

car.i: car.cpp.i
.PHONY : car.i

# target to preprocess a source file
car.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/car.cpp.i
.PHONY : car.cpp.i

car.s: car.cpp.s
.PHONY : car.s

# target to generate assembly for a file
car.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/car.cpp.s
.PHONY : car.cpp.s

car2.o: car2.cpp.o
.PHONY : car2.o

# target to build an object file
car2.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/car2.cpp.o
.PHONY : car2.cpp.o

car2.i: car2.cpp.i
.PHONY : car2.i

# target to preprocess a source file
car2.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/car2.cpp.i
.PHONY : car2.cpp.i

car2.s: car2.cpp.s
.PHONY : car2.s

# target to generate assembly for a file
car2.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/car2.cpp.s
.PHONY : car2.cpp.s

glutwidget.o: glutwidget.cpp.o
.PHONY : glutwidget.o

# target to build an object file
glutwidget.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/glutwidget.cpp.o
.PHONY : glutwidget.cpp.o

glutwidget.i: glutwidget.cpp.i
.PHONY : glutwidget.i

# target to preprocess a source file
glutwidget.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/glutwidget.cpp.i
.PHONY : glutwidget.cpp.i

glutwidget.s: glutwidget.cpp.s
.PHONY : glutwidget.s

# target to generate assembly for a file
glutwidget.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/glutwidget.cpp.s
.PHONY : glutwidget.cpp.s

house.o: house.cpp.o
.PHONY : house.o

# target to build an object file
house.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/house.cpp.o
.PHONY : house.cpp.o

house.i: house.cpp.i
.PHONY : house.i

# target to preprocess a source file
house.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/house.cpp.i
.PHONY : house.cpp.i

house.s: house.cpp.s
.PHONY : house.s

# target to generate assembly for a file
house.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/house.cpp.s
.PHONY : house.cpp.s

lamp.o: lamp.cpp.o
.PHONY : lamp.o

# target to build an object file
lamp.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/lamp.cpp.o
.PHONY : lamp.cpp.o

lamp.i: lamp.cpp.i
.PHONY : lamp.i

# target to preprocess a source file
lamp.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/lamp.cpp.i
.PHONY : lamp.cpp.i

lamp.s: lamp.cpp.s
.PHONY : lamp.s

# target to generate assembly for a file
lamp.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/lamp.cpp.s
.PHONY : lamp.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/main.cpp.s
.PHONY : main.cpp.s

ped.o: ped.cpp.o
.PHONY : ped.o

# target to build an object file
ped.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/ped.cpp.o
.PHONY : ped.cpp.o

ped.i: ped.cpp.i
.PHONY : ped.i

# target to preprocess a source file
ped.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/ped.cpp.i
.PHONY : ped.cpp.i

ped.s: ped.cpp.s
.PHONY : ped.s

# target to generate assembly for a file
ped.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/ped.cpp.s
.PHONY : ped.cpp.s

shader_utils.o: shader_utils.cpp.o
.PHONY : shader_utils.o

# target to build an object file
shader_utils.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/shader_utils.cpp.o
.PHONY : shader_utils.cpp.o

shader_utils.i: shader_utils.cpp.i
.PHONY : shader_utils.i

# target to preprocess a source file
shader_utils.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/shader_utils.cpp.i
.PHONY : shader_utils.cpp.i

shader_utils.s: shader_utils.cpp.s
.PHONY : shader_utils.s

# target to generate assembly for a file
shader_utils.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/shader_utils.cpp.s
.PHONY : shader_utils.cpp.s

skybox.o: skybox.cpp.o
.PHONY : skybox.o

# target to build an object file
skybox.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/skybox.cpp.o
.PHONY : skybox.cpp.o

skybox.i: skybox.cpp.i
.PHONY : skybox.i

# target to preprocess a source file
skybox.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/skybox.cpp.i
.PHONY : skybox.cpp.i

skybox.s: skybox.cpp.s
.PHONY : skybox.s

# target to generate assembly for a file
skybox.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/skybox.cpp.s
.PHONY : skybox.cpp.s

street.o: street.cpp.o
.PHONY : street.o

# target to build an object file
street.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/street.cpp.o
.PHONY : street.cpp.o

street.i: street.cpp.i
.PHONY : street.i

# target to preprocess a source file
street.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/street.cpp.i
.PHONY : street.cpp.i

street.s: street.cpp.s
.PHONY : street.s

# target to generate assembly for a file
street.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/street.cpp.s
.PHONY : street.cpp.s

tree.o: tree.cpp.o
.PHONY : tree.o

# target to build an object file
tree.cpp.o:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/tree.cpp.o
.PHONY : tree.cpp.o

tree.i: tree.cpp.i
.PHONY : tree.i

# target to preprocess a source file
tree.cpp.i:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/tree.cpp.i
.PHONY : tree.cpp.i

tree.s: tree.cpp.s
.PHONY : tree.s

# target to generate assembly for a file
tree.cpp.s:
	$(MAKE) -f CMakeFiles/demo4.x.dir/build.make CMakeFiles/demo4.x.dir/tree.cpp.s
.PHONY : tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... demo4.x"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... building.o"
	@echo "... building.i"
	@echo "... building.s"
	@echo "... car.o"
	@echo "... car.i"
	@echo "... car.s"
	@echo "... car2.o"
	@echo "... car2.i"
	@echo "... car2.s"
	@echo "... glutwidget.o"
	@echo "... glutwidget.i"
	@echo "... glutwidget.s"
	@echo "... house.o"
	@echo "... house.i"
	@echo "... house.s"
	@echo "... lamp.o"
	@echo "... lamp.i"
	@echo "... lamp.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... ped.o"
	@echo "... ped.i"
	@echo "... ped.s"
	@echo "... shader_utils.o"
	@echo "... shader_utils.i"
	@echo "... shader_utils.s"
	@echo "... skybox.o"
	@echo "... skybox.i"
	@echo "... skybox.s"
	@echo "... street.o"
	@echo "... street.i"
	@echo "... street.s"
	@echo "... tree.o"
	@echo "... tree.i"
	@echo "... tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

